### ISSUE TITLE
Explore feasibility of adding a `__version__` attribute

### ISSUE THREAD

**Issue by tfpf** [tfpf/pysorteddict#53]

**Comment by tfpf** [comment]
Can't. Putting

```toml
[tool.setuptools]
ext-modules = [
]
```

in `pyproject.toml` (as per [Building Extension Modules - setuptools 79.0.1.post20250423 documentation](https://setuptools.pypa.io/en/latest/userguide/ext_modules.html)) leads an error saying that this table should not contain `ext-modules`. And putting

```toml
[tool.setuptools.dynamic]
version = [attr = "pysorteddict.__version__"]
```

does not fix it, likely because I am running custom code in `setup.py` which does not supply (and cannot take as dynamic input) the version.
